# Generated by Django 5.2.7 on 2026-02-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('graduation_year', models.IntegerField()),
                ('program', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/alumni/')),
                ('bio', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='AlumniNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_alumni_worldwide', models.IntegerField(default=25000)),
                ('total_countries', models.IntegerField(default=118)),
                ('years_of_excellence', models.IntegerField(default=65)),
                ('description', models.TextField(default='')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alumni Network',
                'verbose_name_plural': 'Alumni Network',
            },
        ),
        migrations.CreateModel(
            name='AlumniSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('graduation_year', models.IntegerField()),
                ('position', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/alumni_success/')),
                ('story_link', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumni', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='success_story', to='alumni.alumni')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
