# Generated by Django 5.2.7 on 2026-02-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Campuses',
                'ordering': ['country', 'city'],
            },
        ),
        migrations.RemoveField(
            model_name='alumninetwork',
            name='total_alumni_worldwide',
        ),
        migrations.RemoveField(
            model_name='alumninetwork',
            name='total_countries',
        ),
        migrations.RemoveField(
            model_name='alumninetwork',
            name='years_of_excellence',
        ),
        migrations.AddField(
            model_name='alumninetwork',
            name='founding_year',
            field=models.IntegerField(default=1960, help_text='Year the institution was founded'),
        ),
    ]
