# Generated by Django 5.2.7 on 2026-01-14 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_heading', models.CharField(default='Our Story', max_length=200)),
                ('story_title', models.CharField(default='Educating Minds, Inspiring Hearts', max_length=200)),
                ('story_content', models.TextField()),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_content', models.TextField()),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Bootstrap icon class, e.g., bi bi-book', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values', to='website.about')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='website.about')),
            ],
            options={
                'ordering': ['order', 'year'],
            },
        ),
    ]
