# Generated by Django 5.2.7 on 2026-01-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_about_corevalue_timelineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Student Life', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('active_students_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Students Life',
                'verbose_name_plural': 'Students Life',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('students_life', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='website.studentslife')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
