# Generated by Django 5.2.7 on 2026-01-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_studentslife_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/website/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/website/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='picture',
            field=models.ImageField(upload_to='media/website/'),
        ),
        migrations.AlterField(
            model_name='studentslife',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/website/'),
        ),
    ]
