# Generated by Django 5.2.7 on 2026-01-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_about_story_image_alter_activity_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_rate', models.IntegerField(default=87, help_text='Alumni employment percentage within 6 months')),
                ('campus_locations', models.IntegerField(default=8, help_text='Number of campus locations')),
                ('awards_received', models.IntegerField(default=250, help_text='Total awards received')),
                ('countries_represented', models.IntegerField(default=65, help_text='Number of countries with students')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
