# Generated by Django 5.2.7 on 2026-01-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_statistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={},
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='awards_received',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='campus_locations',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='countries_represented',
        ),
        migrations.AddField(
            model_name='statistic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='icon',
            field=models.CharField(default=1, help_text='Bootstrap icon class, e.g., bi bi-people', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistic',
            name='success_rate',
            field=models.IntegerField(default=87),
        ),
    ]
