# Generated by Django 5.2.7 on 2026-01-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_statistic_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='updated_at',
        ),
    ]
