# Generated by Django 5.2.7 on 2026-01-18 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_leadership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadership',
            name='content',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='text',
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='website.leadership')),
            ],
        ),
    ]
