# Generated by Django 5.2.7 on 2026-01-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLifeIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Vibrant Campus Experience', max_length=200)),
                ('description_first', models.TextField(help_text='First paragraph of description')),
                ('description_second', models.TextField(blank=True, help_text='Second paragraph of description')),
                ('image', models.ImageField(upload_to='media/website/')),
                ('button_text', models.CharField(default='Explore Campus', max_length=100)),
                ('button_link', models.URLField(blank=True, help_text='URL for explore button')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Life Intro',
                'verbose_name_plural': 'Student Life Intro',
            },
        ),
    ]
