# Generated by Django 5.2.7 on 2026-01-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_studentlifeintro'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Student Organizations & Clubs', max_length=200)),
                ('icon', models.CharField(help_text='Bootstrap icon class, e.g., bi bi-music-note-beamed', max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('badge_text', models.CharField(help_text='e.g., 15+ Groups', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
