# Generated by Django 5.2.7 on 2026-01-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_studentorganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleticsProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Athletics & Recreation', max_length=200)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/website/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
