# Generated by Django 5.2.7 on 2026-01-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_studentlifefacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLifeGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/website/')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Life Gallery Image',
                'verbose_name_plural': 'Student Life Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentSupportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Bootstrap icon class, e.g., bi bi-heart-pulse', max_length=100)),
                ('link', models.URLField(blank=True, help_text='URL for Learn More link')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
