# Generated by Django 5.2.7 on 2026-03-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_studentlifegalleryimage_studentsupportservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=200)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('intro_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True, help_text='Full HTML content for the policy body')),
                ('contact_email', models.EmailField(default='privacy@example.com', max_length=254)),
                ('contact_address', models.CharField(default='123 Privacy Street, Security City, 12345', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policies',
            },
        ),
    ]
