# Generated by Django 5.2.7 on 2026-01-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/staff/')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('work_tile', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
