# Generated by Django 5.2.7 on 2026-01-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/staff/'),
        ),
    ]
