# Generated by Django 5.2.7 on 2026-02-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_staff_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
