# Generated by Django 5.2.7 on 2026-01-26 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/campus/highlights/')),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('research', 'Research'), ('community', 'Community'), ('wellness', 'Wellness'), ('sports', 'Sports')], max_length=20)),
                ('stat1_icon', models.CharField(help_text='Bootstrap icon class', max_length=50)),
                ('stat1_text', models.CharField(max_length=100)),
                ('stat2_icon', models.CharField(help_text='Bootstrap icon class', max_length=50)),
                ('stat2_text', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Discover Our Modern Campus Facilities', max_length=200)),
                ('description', models.TextField(default='Explore our state-of-the-art facilities designed for academic excellence and student success.')),
                ('badge_text', models.CharField(default='Campus Excellence', max_length=100)),
                ('buildings_count', models.CharField(default='95+', max_length=50)),
                ('campus_acres', models.CharField(default='200', max_length=50)),
                ('total_students', models.CharField(default='25k+', max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('map_embed_url', models.URLField(help_text='Google Maps embed URL')),
                ('campus_acres_value', models.CharField(default='32 Acres', max_length=50)),
                ('total_buildings', models.CharField(default='17 Buildings', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Campus Info',
            },
        ),
        migrations.CreateModel(
            name='FacilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Bootstrap icon class (e.g., bi-book)', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Facility Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CampusFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/campus/facilities/')),
                ('amenities', models.TextField(help_text='List amenities separated by newlines')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('capacity', models.CharField(blank=True, help_text='e.g., 500+ students', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='campusfacilities.facilitycategory')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
