# Generated by Django 5.2.7 on 2026-01-26 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusfacilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Take a Virtual Campus Tour', max_length=200)),
                ('description', models.TextField(default='Cras ultricies ligula sed magna dictum porta. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vivamus suscipit tortor eget felis porttitor volutpat.')),
                ('video', models.FileField(help_text='Upload tour video (MP4 format)', upload_to='media/campus/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Or provide video URL if not uploading')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Campus Tours',
            },
        ),
        migrations.CreateModel(
            name='TourFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Bootstrap icon class (e.g., bi-binoculars)', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='campusfacilities.campustour')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
