# Generated by Django 5.2.7 on 2026-01-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusfacilities', '0002_campustour_tourfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusinfo',
            name='image',
            field=models.ImageField(default=1, upload_to='media/campus/'),
            preserve_default=False,
        ),
    ]
