# Generated by Django 5.2.7 on 2026-01-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusfacilities', '0003_campusinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusinfo',
            name='campus_acres_value',
        ),
        migrations.RemoveField(
            model_name='campusinfo',
            name='total_buildings',
        ),
    ]
