# Generated by Django 5.2.7 on 2026-01-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_program_icon'),
        ('addmission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentregistration',
            name='unique_program_student_email',
        ),
        migrations.AlterUniqueTogether(
            name='studentregistration',
            unique_together={('program', 'student_email')},
        ),
    ]
