# Generated by Django 5.2.7 on 2026-01-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission', '0002_remove_studentregistration_unique_program_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finicial', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tuitionprogram',
            name='details',
        ),
        migrations.RemoveField(
            model_name='tuitionprogram',
            name='finicial',
        ),
    ]
