# Generated by Django 5.2.7 on 2026-01-23 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission', '0003_tutionnote_remove_tuitionprogram_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusVisst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/addmission/')),
                ('content', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampusVisitContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(verbose_name=200)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus', to='addmission.campusvisst')),
            ],
        ),
    ]
