# Generated by Django 5.2.7 on 2026-01-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission', '0004_campusvisst_campusvisitcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusvisitcontent',
            name='icon',
            field=models.CharField(default=1, help_text='CSS class for icon, e.g., fa fa-check', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campusvisitcontent',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
