# Generated by Django 5.2.7 on 2026-01-24 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_programintrest'),
        ('addmission', '0005_campusvisitcontent_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationrequest',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='academics.programintrest'),
        ),
        migrations.AlterField(
            model_name='tuitionprogram',
            name='program_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_interest', to='academics.programintrest'),
        ),
        migrations.DeleteModel(
            name='ProgramIntrest',
        ),
    ]
