# Generated by Django 5.2.7 on 2026-01-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_programintrest'),
        ('addmission', '0006_alter_informationrequest_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationrequest',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='academics.program'),
        ),
    ]
