# Generated by Django 5.2.7 on 2026-01-26 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_informationrequest'),
        ('addmission', '0008_alter_informationrequest_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationrequest',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addmission_information_requests', to='academics.programintrest'),
        ),
    ]
