# Generated by Django 5.2.7 on 2026-01-31 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlife', '0001_initial'),
        ('faculty', '0004_staff_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('eventoganizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='faculty.staff')),
                ('fromcategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formcategories', to='eventlife.eventformcategories')),
            ],
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/event/gallery')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('eventgallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventgallery', to='eventlife.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='eventlife.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True)),
                ('end_start', models.TimeField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='eventlife.event')),
            ],
        ),
    ]
