# Generated by Django 5.2.7 on 2026-01-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlife', '0002_eventformcategories_eventform_eventgallery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventschedule',
            old_name='end_start',
            new_name='end_time',
        ),
    ]
