# Generated by Django 5.2.7 on 2026-02-02 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlife', '0003_rename_end_start_eventschedule_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='eventlife.event'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='eventlife.event'),
        ),
    ]
