# Generated by Django 5.2.7 on 2026-02-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlife', '0004_alter_eventhighlight_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='eventgallery',
            options={'ordering': ['-created_date']},
        ),
    ]
