# Generated by Django 5.2.7 on 2026-02-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlife', '0006_eventregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventform',
            name='eventoganizer',
        ),
    ]
