# Generated by Django 5.2.7 on 2026-02-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlife', '0007_remove_eventform_eventoganizer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventForm',
        ),
        migrations.DeleteModel(
            name='EventFormCategories',
        ),
    ]
