# Generated by Django 5.2.7 on 2026-02-04 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlife', '0008_delete_eventform_delete_eventformcategories'),
        ('faculty', '0004_staff_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/event/')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('details', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_no', models.IntegerField(blank=True)),
                ('staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='faculty.staff')),
            ],
        ),
    ]
