# Generated by Django 5.2.7 on 2026-02-04 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlife', '0009_eventorganizer'),
        ('faculty', '0004_staff_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorganizer',
            name='staff',
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='eventstaff',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventstaff', to='faculty.staff'),
            preserve_default=False,
        ),
    ]
