# Generated by Django 5.2.7 on 2026-02-04 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlife', '0010_remove_eventorganizer_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorganizer',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventorganizer', to='eventlife.event'),
            preserve_default=False,
        ),
    ]
