# Generated by Django 5.2.7 on 2026-02-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlife', '0011_eventorganizer_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
