# Generated by Django 5.2.7 on 2026-02-21 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlife', '0013_eventcalender'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcalender',
            name='eventcalender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventcalender', to='eventlife.event'),
            preserve_default=False,
        ),
    ]
