# Generated by Django 5.2.7 on 2026-02-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlife', '0014_eventcalender_eventcalender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='phone_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='EventCalender',
        ),
    ]
