# Generated by Django 5.2.7 on 2026-02-23 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlife', '0016_alter_eventorganizer_eventstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventorganizer', to='eventlife.event'),
        ),
    ]
