# Generated by Django 5.2.7 on 2026-01-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.ImageField(help_text='Program icon/image', upload_to='programs/')),
                ('duration', models.CharField(help_text='e.g., 4 Years', max_length=100)),
                ('degree_type', models.CharField(choices=[('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('certificate', 'Certificate'), ('diploma', 'Diploma')], max_length=20)),
                ('students_count', models.IntegerField(default=0, help_text='Number of students e.g., 450')),
                ('success_rate', models.IntegerField(default=0, help_text='Success rate percentage e.g., 95')),
                ('is_featured', models.BooleanField(default=False, help_text='Display as main featured program')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display in programs grid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
