# Generated by Django 5.2.7 on 2026-01-14 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='students_count',
        ),
        migrations.RemoveField(
            model_name='program',
            name='success_rate',
        ),
        migrations.AlterField(
            model_name='program',
            name='icon',
            field=models.ImageField(help_text='Program icon/image', upload_to='media/'),
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_phone', models.CharField(blank=True, max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], default='enrolled', max_length=20)),
                ('is_passed', models.BooleanField(default=False, help_text='Check if student completed successfully')),
                ('grades', models.CharField(blank=True, help_text='e.g., A, B, C, D, F', max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academics.program')),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'unique_together': {('program', 'student_email')},
            },
        ),
    ]
