# Generated by Django 5.2.7 on 2026-01-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_program_students_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
    ]
