# Generated by Django 5.2.7 on 2026-01-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_delete_studentregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='icon',
            field=models.ImageField(help_text='Program icon/image', upload_to='media/academics/'),
        ),
    ]
