# Generated by Django 5.2.7 on 2026-01-25 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_populate_programintrest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='degree_type',
            field=models.ForeignKey(help_text='Degree type', on_delete=django.db.models.deletion.CASCADE, related_name='degree_programs', to='academics.programintrest'),
        ),
    ]
