# Generated by Django 5.2.7 on 2026-01-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_informationrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformationRequest',
        ),
    ]
